os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: jhcHJATesRSiLsQq21vf2L1KeNpimv1kPqpCJ+CYPffajamAwVlV5/8J2tidQ8oeHE16p2NEpWXAKOHX/nbhCNPdwwenHnjntDcNcya8CyNsYc6M64Yf5fAwYWQtB1uNKk8BqfKCbL+k9PbOI4PCggSs+qmBKvuSiClWN/pSk/b00lbFH0WDMA14sLcN/M95vPPqBD/Fmerd3NuiMnnWoKa3Ps4jImPPW3Y3KV03EhFlt2bmBqts0n69YHINXTJLYavppbs4xj2Q+kQoxkxKl6AP8nBZF6GswgOszi5vmPuealnYPDXyo9YQo4f8iZuSKRYdRmx6IU95NyBEDr5xTIgC5OMbOiQi4rUzPluAcCbv5gbk0A4QQo4WvKr54UiDILUCyxkbQ8zxi9tsL2QqBm45eEkXK4up+gTuzJb5wd+gAN+Ij2F9ZRByCVak7ah5pkuzTaHyRQ94/zaHP9tOWy5XJbEARDq6qxvWy/68BOH/SFYTYD3ysLkEVaSTKrBNoIslOGXGYEfxeyo/UBU7R+nuRmTSzjeMvvRWfgh2B6kVqzzLUJIOqEIw4KiAsUZHiLErp/M9r2f1kJa0W/8g9rg3CsvC/ZmHzUykdBOJQau8KLrHqPxK0GH8m0tHMJssZWcX3HCEdHm4x2hs/X3O3xQgAloIbSz439z0pOvNBxg=
