os: linux
sudo: false
dist: trusty
language: java
jdk: oraclejdk8
cache:
  directories:
  - "~/.m2/repository"
before_install:
- bash .util/build_xatkit.sh
script:
- mvn install
notifications:
  slack:
    secure: cZUKeKcX3qdIMLlhmlyo/Egl/LIchVfay17RdiruTzXcVMeZq/rVWfTiTMcfYyoLyLOg4Ei7TrfCzfMK/GKZEaYIoMh9w54duMV9NYp/AYOohQqwGudQq5YCEvtp2ZFe2eh8RxRgLZ+TiR06esbAzGPiLdTMHCGJ1ktromr5iEZXfAMrgdelsuNCPrx23btFiLsXAs7la/YBN941+/sALqzSS4XZOYms0orRjh6Ux/ucnIWfDDy2jHa7iaA434rRSGF5kcNXtbbzrMLR9kFqZLBJ/qXEWdK5cEKEqp/U65bzvjdK0rhfYpfo81LfpxqMA8D0mR+8ptWTGx7DIL+073+mqETM3UvU9otJVYYoWE/zSib0XTiKBD/3MlLUKWK7tqHAMIwHNdiLa3ou/fw89ghoxJjfGtfrp9MS3qAM3sgjORhiE2RMovXBlA2QzKgw8Dq4eJr+5RT6iANmYsczEZ2ji3DIAIk4AUAe7SyvoKfr5KGbIgXBv/sQfFDvMAe1yfm4DEvoouDSFeJz3ZLjMfBNRSsAbk4aHJ4lgsjt/R0wz57OptAueO+hzzHRXy6O4bz6+0nKcwKF1FauQUOTCkSQEZS1aQeQDD1cDAuZzNayEuPCm8fGxWrtbolBfx+oHsLJpm9f8zwfY90TWseT/5Oj5fzSSO5zNSzckVUEr+w=
